config/routes.rb
Rails.application.routes.draw do

  resources :combinations do
    resources :clusters
  end

  post 'redirect' => 'combinations#redirect'

  root 'welcome#home'

end

app/models/cluster.rb
class Cluster < ActiveRecord::Base
  belongs_to :combination
end

app/models/combination.rb
class Combination < ActiveRecord::Base
	has_many :clusters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  before_action :set_cluster, only: [:show, :edit, :update, :destroy]

  # GET /clusters
  # GET /clusters.json
  def index
    @clusters = Cluster.all
  end

  # GET /clusters/1
  # GET /clusters/1.json
  def show
  end

  # GET /clusters/new
  def new
    @cluster = Cluster.new
  end

  # GET /clusters/1/edit
  def edit
  end

  # POST /clusters
  # POST /clusters.json
  def create
    @cluster = Cluster.new(cluster_params)

    respond_to do |format|
      if @cluster.save
        format.html { redirect_to @cluster, notice: 'Cluster was successfully created.' }
        format.json { render :show, status: :created, location: @cluster }
      else
        format.html { render :new }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clusters/1
  # PATCH/PUT /clusters/1.json
  def update
    respond_to do |format|
      if @cluster.update(cluster_params)
        format.html { redirect_to @cluster, notice: 'Cluster was successfully updated.' }
        format.json { render :show, status: :ok, location: @cluster }
      else
        format.html { render :edit }
        format.json { render json: @cluster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clusters/1
  # DELETE /clusters/1.json
  def destroy
    @cluster.destroy
    respond_to do |format|
      format.html { redirect_to clusters_url, notice: 'Cluster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cluster
      @cluster = Cluster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cluster_params
      params.require(:cluster).permit(:val1, :val2, :val3, :expn_val, :combination_id)
    end
end

app/controllers/combinations_controller.rb
class CombinationsController < ApplicationController
	protect_from_forgery

	before_action :set_combination, only: [:show, :edit, :update, :destroy]

	# GET /combinations
	# GET /combinations.json
	def index
		@combinations = Combination.all

		# params.select! { |k,v| ['age','edu','income','state','occu'].include? k }
		# params.reject! { |k,v| v != 1 }

	end

	def redirect
		array = Array.new(3)
		params[:attr].each do |v| 
			array.push(v)
		end 
		array.reject! { |v| v.nil? || v.empty? }
		array.sort!
		@combination = Combination.where("attr1 = ? AND attr2 = ? AND attr3 = ? AND expn = ?", array[0], array[1], array[2], params[:expn])[0]
		redirect_to @combination
	end

	# GET /combinations/1
	# GET /combinations/1.json
	def show
	end

	# GET /combinations/new
	def new
		@combination = Combination.new
	end

	# GET /combinations/1/edit
	def edit
	end

	# POST /combinations
	# POST /combinations.json
	def create
		@combination = Combination.new(combination_params)

		respond_to do |format|
			if @combination.save
				format.html { redirect_to @combination, notice: 'Combination was successfully created.' }
				format.json { render :show, status: :created, location: @combination }
			else
				format.html { render :new }
				format.json { render json: @combination.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /combinations/1
	# PATCH/PUT /combinations/1.json
	def update
		respond_to do |format|
			if @combination.update(combination_params)
				format.html { redirect_to @combination, notice: 'Combination was successfully updated.' }
				format.json { render :show, status: :ok, location: @combination }
			else
				format.html { render :edit }
				format.json { render json: @combination.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /combinations/1
	# DELETE /combinations/1.json
	def destroy
		@combination.destroy
		respond_to do |format|
			format.html { redirect_to combinations_url, notice: 'Combination was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_combination
			@combination = Combination.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def combination_params
			params.require(:combination).permit(:attr1, :attr2, :attr3, :expn)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clusters_helper.rb
module ClustersHelper
end

app/helpers/combinations_helper.rb
module CombinationsHelper
	def print_val(str)
		if(str.include? '|')
			tmp = "(TOP 3)<br>"
			tokens = str.split('|')
			tokens.each { |token| tmp += "#{token}<br>" }
		else
			tmp = str
		end
		tmp.html_safe
	end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clusters/_form.html.erb
<%= form_for(@cluster) do |f| %>
  <% if @cluster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cluster.errors.count, "error") %> prohibited this cluster from being saved:</h2>

      <ul>
      <% @cluster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :val1 %><br>
    <%= f.text_field :val1 %>
  </div>
  <div class="field">
    <%= f.label :val2 %><br>
    <%= f.text_field :val2 %>
  </div>
  <div class="field">
    <%= f.label :val3 %><br>
    <%= f.text_field :val3 %>
  </div>
  <div class="field">
    <%= f.label :expn_val %><br>
    <%= f.text_field :expn_val %>
  </div>
  <div class="field">
    <%= f.label :combination_id %><br>
    <%= f.text_field :combination_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clusters/edit.html.erb
<h1>Editing Cluster</h1>

<%= render 'form' %>

<%= link_to 'Show', @cluster %> |
<%= link_to 'Back', clusters_path %>

app/views/clusters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clusters</h1>

<table>
  <thead>
    <tr>
      <th>Val1</th>
      <th>Val2</th>
      <th>Val3</th>
      <th>Expn val</th>
      <th>Combination</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clusters.each do |cluster| %>
      <tr>
        <td><%= cluster.val1 %></td>
        <td><%= cluster.val2 %></td>
        <td><%= cluster.val3 %></td>
        <td><%= cluster.expn_val %></td>
        <td><%= cluster.combination %></td>
        <td><%= link_to 'Show', cluster %></td>
        <td><%= link_to 'Edit', edit_cluster_path(cluster) %></td>
        <td><%= link_to 'Destroy', cluster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cluster', new_cluster_path %>

app/views/clusters/new.html.erb
<h1>New Cluster</h1>

<%= render 'form' %>

<%= link_to 'Back', clusters_path %>

app/views/clusters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Val1:</strong>
  <%= @cluster.val1 %>
</p>

<p>
  <strong>Val2:</strong>
  <%= @cluster.val2 %>
</p>

<p>
  <strong>Val3:</strong>
  <%= @cluster.val3 %>
</p>

<p>
  <strong>Expn val:</strong>
  <%= @cluster.expn_val %>
</p>

<p>
  <strong>Combination:</strong>
  <%= @cluster.combination %>
</p>

<%= link_to 'Edit', edit_cluster_path(@cluster) %> |
<%= link_to 'Back', clusters_path %>

app/views/combinations/_form.html.erb
<%= form_for(@combination) do |f| %>
  <% if @combination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@combination.errors.count, "error") %> prohibited this combination from being saved:</h2>

      <ul>
      <% @combination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attr1 %><br>
    <%= f.text_field :attr1 %>
  </div>
  <div class="field">
    <%= f.label :attr2 %><br>
    <%= f.text_field :attr2 %>
  </div>
  <div class="field">
    <%= f.label :attr3 %><br>
    <%= f.text_field :attr3 %>
  </div>
  <div class="field">
    <%= f.label :expn %><br>
    <%= f.text_field :expn %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/combinations/edit.html.erb
<h1>Editing Combination</h1>

<%= render 'form' %>

<%= link_to 'Show', @combination %> |
<%= link_to 'Back', combinations_path %>

app/views/combinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Combinations</h1>

<form class="form-horizontal" action="/redirect" method="post">
	<div class="form-group">
		<label for="age-box" class="col-sm-2 control-label">Input</label>
		<div id="input" class="col-sm-2" data-container="body" data-toggle="popover" data-placement="right" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus.">
			<div class="checkbox">
				<label>
					<input type="checkbox" class="form-control" id="age-box" name="attr[]" onClick="return KeepCount()" value="age" checked="checked">Age<br>
				</label>
			</div>

			<div class="checkbox">
				<label>
					<input type="checkbox" name="attr[]" onClick="return KeepCount()" value="edu" checked="checked">Education<br>
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="attr[]" onClick="return KeepCount()" value="income" checked="checked">Income<br>
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="attr[]" onClick="return KeepCount()" value="occu">Occupation<br>
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="attr[]" onClick="return KeepCount()" value="state">State<br>
				</label>
			</div>
		</div>
		<label for="car-box" class="col-sm-2 control-label">Output</label>
		<div class="col-sm-2">
			<div class="radio">
				<label>
					<input type="radio" name="expn" value="car" checked="checked">Car<br>

				</label>
			</div>
		</div>
		<button type="submit" class="btn btn-primary col-sm-2">Submit</button>
	</div>
	
	
</form>


<table>
	<thead>
		<tr>
			<th>Attr1</th>
			<th>Attr2</th>
			<th>Attr3</th>
			<th>Expn</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @combinations.each do |combination| %>
			<tr>
				<td><%= combination.attr1 %></td>
				<td><%= combination.attr2 %></td>
				<td><%= combination.attr3 %></td>
				<td><%= combination.expn %></td>
				<td><%= link_to 'Show', combination %></td>
				<td><%= link_to 'Edit', edit_combination_path(combination) %></td>
				<td><%= link_to 'Destroy', combination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Combination', new_combination_path %>
<script type="text/javascript">

	$('input[type=checkbox]').on('change', function (e) {
	    if ($('input[type=checkbox]:checked').length > 3) {
	        $(this).prop('checked', false);
	        alert("allowed only 3");
	    }
	});

</script>

app/views/combinations/new.html.erb
<h1>New Combination</h1>

<%= render 'form' %>

<%= link_to 'Back', combinations_path %>

app/views/combinations/show.html.erb
<div class="inner-wrapper">
	<p id="notice"><%= notice %></p>

	<p>
		<strong>Input: </strong>
		<%= @combination.attr1 %>
		<%= @combination.attr2 %>
		<%= @combination.attr3 %>
	</p>

	<p>
		<strong>Expenditure: </strong>
		<%= @combination.expn %>
	</p>
	<br>
	<% i = 0 %>
	<% @combination.clusters.each do |cluster| %>
		<% i += 1 %>
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><%= "CLUSTER #{i}" %></h3>
			</div>
			<div class="panel-body">
				<p>
				  <strong><%= @combination.attr1.upcase %></strong>
				  <%= print_val(cluster.val1) %>
				</p>

				<p>
				  <strong><%= @combination.attr2.upcase %></strong>
				  <%= print_val(cluster.val2) %>
				</p>

				<p>
				  <strong><%= @combination.attr3.upcase %></strong>
				  <%= print_val(cluster.val3) %>
				</p>

				<p>
				  <strong><%= @combination.expn.upcase %></strong>
				  <%= print_val(cluster.expn_val) %>
				</p>
			</div>
		</div>

	<% end %>

	<%= link_to 'Edit', edit_combination_path(@combination) %> |
	<%= link_to 'Back', combinations_path %>

</div>

app/views/layouts/_footer.html.erb
<footer>

	<center>Columbia University | Big Data Analytics</center>

</footer>

app/views/layouts/_header.html.erb
<header id="nav" class="navbar-fixed-top">
	<div class="navbar-header">
		
		<a id="logo" href=<%= root_url%>>SAPPHIRINE</a>
		
	</div>
	<ul class="nav navbar-nav pull-right">
		
		<li><%= link_to "Our Project", "#"%></li>
		<li><%= link_to "Clusters", combinations_path%></li>
		<li><%= link_to "Cars", "#"%></li>

	</ul>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sapphirine</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header'%>
	
	<div class="container-fluid" id="wrapper">

		<div class="row-fluid">
			<%= yield%>
		</div>
	</div>

	<%= render 'layouts/footer'%>
</body>
</html>

app/views/welcome/home.html.erb
<div class="span10 offset1">
	<div id="my-carousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
		<li data-target="#my-carousel" data-slide-to="0" class="active"></li>
		<li data-target="#my-carousel" data-slide-to="1"></li>
		<li data-target="#my-carousel" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<%= image_tag("bigdata.png", :alt => "bigdata") %>
				<div class="carousel-caption">
					<h3>Test</h3>
				</div>
			</div>
			<div class="item">
				<%= image_tag("people.jpg", :alt => "people") %>
				<div class="carousel-caption">
					<h3>Test</h3>
				</div>
			</div>
			<div class="item">
				<%= image_tag("cars.png", :alt => "cars") %>
				<div class="carousel-caption">
					<h3>Test</h3>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid need-padding">
		<div class="col-md-4">
			<h2>Heading</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			<p>
				<a class="btn btn-default" href="#" role="button">View details</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>Heading</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			<p>
				<a class="btn btn-default" href="#" role="button">View details</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>Heading</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			<p>
				<a class="btn btn-default" href="#" role="button">View details</a>
			</p>
		</div>
	</div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
		    $('.carousel').carousel({
				interval: 3000
			});
		});
	</script>

</div>

app/views/welcome/index.html.erb
<div class="span10 offset1">
	<div id="my-carousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
		<li data-target="#my-carousel" data-slide-to="0" class="active"></li>
		<li data-target="#my-carousel" data-slide-to="1"></li>
		<li data-target="#my-carousel" data-slide-to="2"></li>
		</ol>

		<!-- Wrapper for slides -->
		<div class="carousel-inner" role="listbox">
			<div class="item active">
				<%= image_tag("bigdata.png", :alt => "bigdata") %>
				<div class="carousel-caption">
					<h3>Test</h3>
				</div>
			</div>
			<div class="item">
				<%= image_tag("people.jpg", :alt => "people") %>
				<div class="carousel-caption">
					<h3>Test</h3>
				</div>
			</div>
			<div class="item">
				<%= image_tag("cars.png", :alt => "cars") %>
				<div class="carousel-caption">
					<h3>Test</h3>
				</div>
			</div>
		</div>

		<!-- Controls -->
		<a class="left carousel-control" href="#my-carousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
			<a class="right carousel-control" href="#my-carousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	<div class="row-fluid need-padding">
		<div class="col-md-4">
			<h2>Heading</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			<p>
				<a class="btn btn-default" href="#" role="button">View details</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>Heading</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			<p>
				<a class="btn btn-default" href="#" role="button">View details</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>Heading</h2>
			<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
			<p>
				<a class="btn btn-default" href="#" role="button">View details</a>
			</p>
		</div>
	</div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function(){
		    $('.carousel').carousel({
				interval: 3000
			});
		});
	</script>

</div>